name: Build Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: make build
  yarn-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run yarn audit
        run: |
          yarn audit
          audit_exit_code=$?

          if [ $audit_exit_code -le 6 ]; then
              # Exit with 0
              exit 0
          else
              # Exit with 1
              exit 1
          fi
